mac

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -1,59 +1,128 @@
-#!/bin/bash
+#!/bin/sh
 set -e
 
-if ! [ $# -eq 13 ]; then
+all(){
 
-    echo "make sure to download debian cloud image : rm debian-12-nocloud-amd64.raw && wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.raw"
+    if ! [ $# -eq 13 ]; then
 
-    echo "Usage: sudo $0 <INSIDE_MACHINE> <CREATE_USER> <TARGET_USERNAME> <TARGET_PASSWD> <AUTHSSHFILE> <DOCKER_HOST> <KUBE_HOST> <GUI> <BLACKLIST_NOUVEAU> <NVIDIA_DRIVERS> <INPUT_IMG> <OUTPUT_IMAGE> <DISK_SIZE>"
-    echo "baremetal fullgui:    sudo $0 1 0 apham ps authorized_keys 1 1 1 1 1 debian-12-nocloud-amd64.raw d12-fgui.raw 5G"
-    echo "cloud fullgui:        sudo $0 0 1 apham ps authorized_keys 1 1 1 1 0 debian-12-nocloud-amd64.raw d12-fgui.raw 5G"
-    echo "cloud full:           sudo $0 0 1 apham ps authorized_keys 1 1 0 1 0 debian-12-nocloud-amd64.raw d12-full.raw 5G"
-    echo "cloud image min:      sudo $0 0 1 apham ps authorized_keys 0 0 0 1 0 debian-12-nocloud-amd64.raw d12-mini.raw 3G"
-    echo "cloud image kube:     sudo $0 0 1 apham ps authorized_keys 0 1 0 1 0 debian-12-nocloud-amd64.raw d12-kube.raw 4G"
+        echo "make sure to download debian cloud image : rm debian-12-nocloud-amd64.raw && wget https://cloud.debian.org/images/cloud/bookworm/latest/debian-12-nocloud-amd64.raw"
 
-    exit 1
-fi
+        echo "Usage: sudo $0 <INSIDE_MACHINE> <CREATE_USER> <TARGET_USERNAME> <TARGET_PASSWD> <AUTHSSHFILE> <DOCKER_HOST> <KUBE_HOST> <GUI> <BLACKLIST_NOUVEAU> <NVIDIA_DRIVERS> <INPUT_IMG> <OUTPUT_IMAGE> <DISK_SIZE>"
+        echo "baremetal fullgui:    sudo all 1 0 apham ps authorized_keys 1 1 1 1 1 debian-12-nocloud-amd64.raw d12-fgui.raw 5G"
+        echo "cloud fullgui:        sudo all 0 1 apham ps authorized_keys 1 1 1 1 0 debian-12-nocloud-amd64.raw d12-fgui.raw 5G"
+        echo "cloud full:           sudo all 0 1 apham ps authorized_keys 1 1 0 1 0 debian-12-nocloud-amd64.raw d12-full.raw 5G"
+        echo "cloud image min:      sudo all 0 1 apham ps authorized_keys 0 0 0 1 0 debian-12-nocloud-amd64.raw d12-mini.raw 3G"
+        echo "cloud image kube:     sudo all 0 1 apham ps authorized_keys 0 1 0 1 0 debian-12-nocloud-amd64.raw d12-kube.raw 4G"
 
-setversions() {
-# https://github.com/docker/buildx/releases
-export DOCKER_BUILDX_VERSION=v0.17.1
-# https://kubernetes.io/releases/  https://cloud.google.com/kubernetes-engine/docs/release-notes
-export MAJOR_KUBE_VERSION=v1.30
-# https://github.com/derailed/k9s/releases
-export K9S_VERSION=v0.32.5
-# https://maven.apache.org/download.cgi
-export MVN_VERSION=3.9.9
+        return
+    fi
 
-export NERDFONTS="ComicShannsMono FiraMono JetBrainsMono"
+    init $@
+    mountraw
+    createuser
+    authkeys
+    rmnouveau
+    fastboot
+    firstbootexpandfs
+    bashaliases
+    smalllogs
+    aptsrc
+    iessentials
+    isudo
+    ikeyboard
+    idocker
+    ikube
+    idlkubeimg
+    invidia
+    igui
+    cleanupapt
+    unmountraw
 }
 
-setversions
-
-setkeyboard() {
-export KEYBOARD_LAYOUT=fr
+baremetalfullgui() {
+    # Set the default values
+    all 1 0 apham x x 1 1 1 1 1 x x
 }
 
-setkeyboard
+cloudfull() {
+    all 0 1 apham ps authorized_keys 1 1 0 1 0 debian-12-nocloud-amd64.raw d12-full.raw 5G
+}
 
-setinput() {
-#default root
-export ROOTFS=/
+cloudmin() {
+    all 0 1 apham ps authorized_keys 0 0 0 1 0 debian-12-nocloud-amd64.raw d12-mini.raw 3G
+}
 
-# Map input parameters
-export INSIDE_MACHINE=$1
-export CREATE_USER=$2
-export TARGET_USERNAME=$3
-export TARGET_PASSWD=$4
-export AUTHSSHFILE=$5
-export DOCKER_HOST=$6
-export KUBE_HOST=$7
-export GUI=$8
-export BLACKLIST_NOUVEAU=$9
-export NVIDIA_DRIVERS=${10}
-export INPUT_IMG=${11}
-export OUTPUT_IMAGE=${12}
-export DISK_SIZE=${13}
+clouddocker(){
+    all 0 1 apham ps authorized_keys 1 0 0 1 0 debian-12-nocloud-amd64.raw d12-docker.raw 4G
+}
+
+cloudkube() {
+    all 0 1 apham ps authorized_keys 0 1 0 1 0 debian-12-nocloud-amd64.raw d12-kube.raw 4G
+}
+
+
+init() {
+    # Set the default values
+    inputversions
+    inputkeyboard
+    inputtasks $@
+}
+
+inputversions() {
+    # https://github.com/docker/buildx/releases
+    export DOCKER_BUILDX_VERSION=v0.17.1
+    echo "export DOCKER_BUILDX_VERSION=${DOCKER_BUILDX_VERSION}"
+    # https://kubernetes.io/releases/  https://cloud.google.com/kubernetes-engine/docs/release-notes
+    export MAJOR_KUBE_VERSION=v1.30
+    echo "export MAJOR_KUBE_VERSION=${MAJOR_KUBE_VERSION}"
+    # https://github.com/derailed/k9s/releases
+    export K9S_VERSION=v0.32.5
+    echo "export K9S_VERSION=${K9S_VERSION}"
+    # https://maven.apache.org/download.cgi
+    export MVN_VERSION=3.9.9
+    echo "export MVN_VERSION=${MVN_VERSION}"
+
+    export NERDFONTS="ComicShannsMono FiraMono JetBrainsMono"
+    echo "export NERDFONTS=${NERDFONTS}"
+}
+
+inputkeyboard() {
+    export KEYBOARD_LAYOUT=fr
+    echo "export KEYBOARD_LAYOUT=${KEYBOARD_LAYOUT}"
+}
+
+
+inputtasks() {
+    #default root
+    export ROOTFS=/
+    echo "export ROOTFS=${ROOTFS}"
+    # Map input parameters
+    export INSIDE_MACHINE=$1
+    echo "export INSIDE_MACHINE=${INSIDE_MACHINE}"
+    export CREATE_USER=$2
+    echo "export CREATE_USER=${CREATE_USER}"
+    export TARGET_USERNAME=$3
+    echo "export TARGET_USERNAME=${TARGET_USERNAME}"
+    export TARGET_PASSWD=$4
+    echo "export TARGET_PASSWD=${TARGET_PASSWD}"
+    export AUTHSSHFILE=$5
+    echo "export AUTHSSHFILE=${AUTHSSHFILE}"
+    export DOCKER_HOST=$6
+    echo "export DOCKER_HOST=${DOCKER_HOST}"
+    export KUBE_HOST=$7
+    echo "export KUBE_HOST=${KUBE_HOST}"
+    export GUI=$8
+    echo "export GUI=${GUI}"
+    export BLACKLIST_NOUVEAU=$9
+    echo "export BLACKLIST_NOUVEAU=${BLACKLIST_NOUVEAU}"
+    export NVIDIA_DRIVERS=${10}
+    echo "export NVIDIA_DRIVERS=${NVIDIA_DRIVERS}"
+    export INPUT_IMG=${11}
+    echo "export INPUT_IMG=${INPUT_IMG}"
+    export OUTPUT_IMAGE=${12}
+    echo "export OUTPUT_IMAGE=${OUTPUT_IMAGE}"
+    export DISK_SIZE=${13}
+    echo "export DISK_SIZE=${DISK_SIZE}"
 }
 
 lineinfile() {
@@ -68,13 +137,13 @@ lineinfile() {
 
     # Check if the file exists
     if [[ ! -f "$file_path" ]]; then
-        echo "File not found creating file !"
         if [ $create_file -eq 1 ]; then
+            echo "File not found creating file !"
             touch "$file_path"
         else
             return 1
         fi
-    else
+    fi
 
     # Check if the line matching the regex exists in the file
     if grep -qE "$regex" "$file_path"; then
@@ -86,70 +155,62 @@ lineinfile() {
         echo "$new_line" >> "$file_path"
         echo "New line added : $new_line"
     fi
+    
 }
 
+mountraw() {
+    # Only execute when working with a raw image
+    if [ $INSIDE_MACHINE -eq 0 ]; then
 
+    # name devices
+    export DEVICE=/dev/loop0
+    export ROOTFS="/tmp/installing-rootfs"
 
-appendinfileiflineexist(){
-    local file_path="$1"   # First argument: file path
-    local regex="$2"       # Second argument: regex to search for
-    local new_line="$3"    # Third argument: new line to replace or add
+    # resize image
+    cp $INPUT_IMG $OUTPUT_IMAGE
+    qemu-img  resize -f raw $OUTPUT_IMAGE $DISK_SIZE
 
+    # setup loopback
+    losetup -D 
+    losetup -fP $OUTPUT_IMAGE
+
+    # fix partition
+    printf "fix\n" | parted ---pretend-input-tty $DEVICE print
+    growpart ${DEVICE} 1
+    resize2fs ${DEVICE}p1
+
+    # mount image for chroot
+    echo "Mount OS partition"
+    mkdir -p ${ROOTFS}
+    mount ${DEVICE}p1 ${ROOTFS}
+    mount ${DEVICE}p15 ${ROOTFS}/boot/efi
+
+    echo "Get ready for chroot"
+    mount --bind /dev ${ROOTFS}/dev
+    mount --bind /run ${ROOTFS}/run
+
+    mount -t devpts /dev/pts ${ROOTFS}/dev/pts
+    mount -t proc proc ${ROOTFS}/proc
+    mount -t sysfs sysfs ${ROOTFS}/sys
+    mount -t tmpfs tmpfs ${ROOTFS}/tmp
+    fi 
 }
 
+createuser() {
 
-
-# Only execute when working with a raw image
-if [ $INSIDE_MACHINE -eq 0 ]; then
-
-# name devices
-export DEVICE=/dev/loop0
-export ROOTFS="/tmp/installing-rootfs"
-
-# resize image
-cp $INPUT_IMG $OUTPUT_IMAGE
-
-qemu-img  resize -f raw $OUTPUT_IMAGE $DISK_SIZE
-
-
-# setup loopback
-losetup -D 
-losetup -fP $OUTPUT_IMAGE
-
-# fix partition
-if [ $DOCKER_HOST -eq 1 ] || [ $KUBE_HOST -eq 1 ] ; then
-printf "fix\n" | parted ---pretend-input-tty $DEVICE print
-growpart ${DEVICE} 1
-resize2fs ${DEVICE}p1
-fi
-
-
-# mount image for chroot
-echo "Mount OS partition"
-mkdir -p ${ROOTFS}
-mount ${DEVICE}p1 ${ROOTFS}
-mount ${DEVICE}p15 ${ROOTFS}/boot/efi
-
-echo "Get ready for chroot"
-mount --bind /dev ${ROOTFS}/dev
-mount --bind /run ${ROOTFS}/run
-
-mount -t devpts /dev/pts ${ROOTFS}/dev/pts
-mount -t proc proc ${ROOTFS}/proc
-mount -t sysfs sysfs ${ROOTFS}/sys
-mount -t tmpfs tmpfs ${ROOTFS}/tmp
-fi 
-
-# create user and setup ssh
 if [ $CREATE_USER -eq 1 ]; then
 export TARGET_ENCRYPTED_PASSWD=$(openssl passwd -6 -salt xyz $TARGET_PASSWD)
-echo "chroot setup users"
+echo "setup users"
 cat << EOF | chroot ${ROOTFS}
     /usr/sbin/useradd -m -s /bin/bash $TARGET_USERNAME
     echo '${TARGET_USERNAME}:${TARGET_ENCRYPTED_PASSWD}' | /usr/sbin/chpasswd -e
     echo 'root:${TARGET_ENCRYPTED_PASSWD}' | /usr/sbin/chpasswd -e
 EOF
 fi
+
+}
+
+authkeys() {
 
 if [ -f $AUTHSSHFILE ]; then
 mkdir -p ${ROOTFS}/home/$TARGET_USERNAME/.ssh/
@@ -159,18 +220,31 @@ cat << EOF | chroot ${ROOTFS}
 EOF
 fi
 
+}
+
+rmnouveau() {
 
 # deactivate nouveau drivers 
 if [ $BLACKLIST_NOUVEAU -eq 1 ]; then
-    sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/ {/modprobe.blacklist=nouveau/! s/"$/ modprobe.blacklist=nouveau"/}' ${ROOTFS}/etc/default/grub
+sed -i '/GRUB_CMDLINE_LINUX_DEFAULT/ {/modprobe.blacklist=nouveau/! s/"$/ modprobe.blacklist=nouveau"/}' ${ROOTFS}/etc/default/grub
+cat << EOF | chroot ${ROOTFS}
+    update-grub
+EOF
 fi
 
+}
+
+fastboot() {
+
 # accelerate grub startup
+echo 'GRUB_TIMEOUT=0' | tee -a ${ROOTFS}/etc/default/grub.d/15_timeout.cfg
 cat << EOF | chroot ${ROOTFS}
-    echo 'GRUB_TIMEOUT=0' | tee -a /etc/default/grub.d/15_timeout.cfg
     update-grub
 EOF
 
+}
+
+firstbootexpandfs() {
 if [ $INSIDE_MACHINE -eq 0 ]; then
 # first boot script
 cat <<EOF | tee ${ROOTFS}/usr/local/bin/firstboot.sh
@@ -207,7 +281,9 @@ cat << EOF | chroot ${ROOTFS}
 EOF
 fi
 
-# super aliases
+}
+
+bashaliases() {
 
 lineinfile ${ROOTFS}/etc/bash.bashrc ".*alias.*ll.*=.*" 'alias ll="ls -larth"'
 lineinfile ${ROOTFS}/etc/bash.bashrc ".*export.*ROOTFS*=.*" 'export ROOTFS=\/'
@@ -218,17 +294,23 @@ lineinfile ${ROOTFS}/etc/bash.bashrc ".*export.*K9S_VERSION*=.*" "export K9S_VER
 lineinfile ${ROOTFS}/etc/bash.bashrc ".*export.*MVN_VERSION*=.*" "export MVN_VERSION=${MVN_VERSION}"
 lineinfile ${ROOTFS}/etc/bash.bashrc ".*export.*NERDFONTS*=.*" "export NERDFONTS=${NERDFONTS}"
 
+}
 
+smalllogs() {
 echo "lower log volume"
 lineinfile ${ROOTFS}/etc/systemd/journald.conf ".*SystemMaxUse=.*" "SystemMaxUse=50M"
+}
 
+aptsrc() {
 echo "setup apt"
 cat <<EOF > ${ROOTFS}/etc/apt/sources.list
 deb http://deb.debian.org/debian bookworm main contrib non-free non-free-firmware
 deb http://deb.debian.org/debian-security/ bookworm-security main contrib non-free non-free-firmware
 deb http://deb.debian.org/debian bookworm-updates main contrib non-free non-free-firmware
 EOF
+}
 
+iessentials() {
 # Essentials packages
 echo "install essentials"
 cat << EOF | chroot ${ROOTFS}
@@ -237,7 +319,9 @@ cat << EOF | chroot ${ROOTFS}
     DEBIAN_FRONTEND=noninteractive apt install -y cloud-guest-utils openssh-server console-setup
 EOF
 
-echo "setup sudo user"
+}
+
+isudo() {
 cat << EOF | chroot ${ROOTFS}
     echo '${TARGET_USERNAME} ALL=(ALL) NOPASSWD:ALL' | sudo EDITOR='tee -a' visudo -f /etc/sudoers.d/nopwd
 EOF
@@ -246,6 +330,9 @@ cat << EOF | chroot ${ROOTFS}
     sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
 EOF
 
+}
+
+ikeyboard() {
 if [  $INSIDE_MACHINE -eq 0 ]; then
 # setup keyboard
 cat <<EOF | tee ${ROOTFS}/etc/default/keyboard
@@ -261,13 +348,16 @@ XKBLAYOUT="${KEYBOARD_LAYOUT}"
 # BACKSPACE="guess"
 EOF
 fi
+}
+
+idocker () {
 
 if [ $DOCKER_HOST -eq 1 ]; then
 
 echo "install docker"
 cat << EOF | chroot ${ROOTFS}
     apt install -y docker.io python3-docker docker-compose skopeo
-    apt install -y ansible openjdk-17-jdk-headless ntfs-3g
+    apt install -y ansible openjdk-17-jdk-headless
 EOF
 
 cat <<EOF | tee ${ROOTFS}/etc/docker/daemon.json
@@ -304,11 +394,6 @@ cat << EOF | chroot ${ROOTFS}
 EOF
 rm /tmp/maven.tar.gz
 
-
-
-# TODO on first boot : 
-# docker network create --opt com.docker.network.bridge.name=primenet --driver=bridge --subnet=172.18.0.0/16 --gateway=172.18.0.1 primenet
-# docker buildx create --name multibuilder --platform linux/amd64,linux/arm/v7,linux/arm64/v8 --use
 
 cat <<EOF | tee ${ROOTFS}/usr/local/bin/firstboot-dockernet.sh
 #!/bin/bash
@@ -378,7 +463,10 @@ cat << EOF | chroot ${ROOTFS}
 EOF
 
 fi
+}
 
+ikube() {
+ 
 if [ $KUBE_HOST -eq 1 ]; then
 
 echo "install kube readiness"
@@ -428,11 +516,20 @@ cat << EOF | chroot ${ROOTFS}
     rm k9s_Linux_amd64.tar.gz
 EOF
 
+fi
+   
+}
+
+idlkubeimg() {
+if [ $KUBE_HOST -eq 1 ]; then
 echo "download kube images"
 cat << EOF | chroot ${ROOTFS}
     kubeadm config images pull
 EOF
 fi
+}
+
+invidia() {
 
 if [ $NVIDIA_DRIVERS -eq 1 ]; then
 echo "install nvidia drivers"
@@ -447,6 +544,10 @@ cat << EOF | chroot ${ROOTFS}
     apt install -y $NV_VERSION
 EOF
 fi
+
+}
+
+igui() {
 
 if [ $GUI -eq 1 ]; then
 echo "install gui"
@@ -467,9 +568,10 @@ done
  
 echo "additional gui packages"
 cat << EOF | chroot ${ROOTFS}
-    apt install -y mpv vlc cmatrix nmon mesa-utils neofetch nitrogen 
+    apt install -y ntfs-3g mpv vlc cmatrix nmon mesa-utils neofetch nitrogen
 EOF
 
+#begin dwm
 if [ ! -d ${ROOTFS}/home/$TARGET_USERNAME/wm ] ; then
 
 echo "The does not exist, installing dwm"
@@ -480,9 +582,9 @@ cat << EOF | chroot ${ROOTFS}
     git clone https://github.com/alainpham/st-flexipatch.git
     git clone https://github.com/alainpham/dmenu-flexipatch.git
 
-    cd /home/$TARGET_USERNAME/wm/dwm-${DWM_VERSION} && make clean install
-    cd /home/$TARGET_USERNAME/wm/st-${ST_VERSION} && make clean install
-    cd /home/$TARGET_USERNAME/wm/dmenu-${DMENU_VERSION} && make clean install
+    cd /home/$TARGET_USERNAME/wm/dwm-flexipatch && make clean install
+    cd /home/$TARGET_USERNAME/wm/st-flexipatch && make clean install
+    cd /home/$TARGET_USERNAME/wm/dmenu-flexipatch && make clean install
 
     chown -R $TARGET_USERNAME:$TARGET_USERNAME /home/$TARGET_USERNAME/wm
 EOF
@@ -511,12 +613,18 @@ fi
 
 # end gui
 fi
+ 
+}
 
-
+cleanupapt() {
 echo "cleaning up"
 cat << EOF | chroot ${ROOTFS}
     apt-get clean && rm -rf /var/lib/apt/lists/*
 EOF
+}
+
+
+unmountraw() {
 
 if [ $INSIDE_MACHINE -eq 0 ]; then
 echo "Unmounting filesystems"
@@ -526,3 +634,4 @@ losetup -D
 fi
 
 
+}
